package com.team7trek.trekDemo;
import com.team7trek.trekDemo.models.Continent;
import com.team7trek.trekDemo.models.Region;
import com.team7trek.trekDemo.models.Trek;
import com.team7trek.trekDemo.repositories.ContinentRepository;
import com.team7trek.trekDemo.repositories.RegionRepository;
import com.team7trek.trekDemo.repositories.TrekRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;
import javax.annotation.Resource;

@Component
public class Populator implements CommandLineRunner {
    @Resource
    private TrekRepository trekRepo;
    @Resource
    private ContinentRepository continentRepo;
    @Resource
    private RegionRepository regionRepo;
    @Override
    public void run(String... args) throws Exception {
        Continent northAmerica = new Continent("North America","/images/na.jpg");
        Continent southAmerica = new Continent("South America","/images/sa2.jpg");
        Continent europe = new Continent("Europe","/images/eu1.jpg");
        Continent asia = new Continent("Asia","/images/asia.jpg");
        Continent antarctica = new Continent("Antarctica","/images/snow2.jpg");
        Continent africa = new Continent("Africa","/images/africa.jpg");
        Continent australia = new Continent("Australia","/images/peace.jpg");
        continentRepo.save(northAmerica);
        continentRepo.save(southAmerica);
        continentRepo.save(europe);
        continentRepo.save(asia);
        continentRepo.save(antarctica);
        continentRepo.save(africa);
        continentRepo.save(australia);
        Region northAmerica1 = new Region("NorthAmerica1","climate","/images/na2.jpg",northAmerica);
        Region northAmerica2 = new Region("NorthAmerica2","climate","/images/trees.jpg",northAmerica);
        Region southAmerica2 = new Region("SouthAmerica1","climate","/images/CopperCanyon.jpg",southAmerica);
        Region southAmerica1 = new Region("SouthAmerica2","climate","/images/sa1.jpg",southAmerica);
        Region europe1 = new Region("Europe1","climate","/images/eu2.jpg",europe);
        Region europe2 = new Region("Europe2","climate","/images/eu1.jpg",europe);
        Region asia1 = new Region("Asia1", "climate","/images/asia.jpg",asia);
        Region asia2 = new Region("Asia2", "climate","/images/asia1.jpg",asia);
        Region antarctica1 = new Region("Ant1","climate","/images/snow.jpg",antarctica);
        Region antarctica2 = new Region("Ant2","climate","/images/snow.jpg",antarctica);
        Region africa1 = new Region("Africa1","climate","/images/africa1.jpg",africa);
        Region africa2 = new Region("Africa2","climate","/images/africa.jpg",africa);
        Region australia1 = new Region("Australia1","climate","/images/desert.jpg",australia);
        Region australia2 = new Region("Australia2","climate","/images/desert1.jpg",australia);
        regionRepo.save(northAmerica1);
        regionRepo.save(northAmerica2);
        regionRepo.save(southAmerica1);
        regionRepo.save(southAmerica2);
        regionRepo.save(europe1);
        regionRepo.save(europe2);
        regionRepo.save(asia1);
        regionRepo.save(asia2);
        regionRepo.save(antarctica1);
        regionRepo.save(antarctica2);
        regionRepo.save(africa1);
        regionRepo.save(africa2);
        regionRepo.save(australia1);
        regionRepo.save(australia2);
        Trek na1 = new Trek("Killer Kayaking","2/5","Just north of Vancouver Island, BC hundreds of orca (killer) whales migrate. Telegraph Cove is a world renowned place for kayaking with the whales.","Exhilarating and terrifying. There is something amazing about watching these huge masters of the ocean, but to be near them is to remind you how small a part of the world you are.","/images/killerkayaking.jpg",northAmerica,northAmerica1);
        Trek na2 = new Trek("Waterfall Repelling","4/5","Waterfall repelling or canyoning is one of Costa Rica's most thrilling adventure sports. This TREK involves a romp through a beautiful rainforest and a descent into crystalline water that will satisify even the biggest adrenaline junkies and leave you begging to do it all over again.","Amazing once in a lifetime views and experiences. Challenging but worth it in the end.","/images/killerkayaking.jpg",northAmerica,northAmerica1);
        Trek na3 = new Trek("Copper Canyon","3/5","The longest (3km), highest (300 meters) and fastest (120 km per hour) zipline in the world is in the Copper Canyon Adventure Park (Parque de Aventuras) near Divisadero.This is part of a system of seven ziplines and two suspension bridges. Other optional activities at the park include a trip in a cable car and a Via Ferrata that allows you to scale and rappel the wall of the canyon. Enjoy the beauty of the canyon and get an adrenaline rush at the same time!","The most wonderful and enchanted places you will ever visit! The people, views and food are awesome. Its a place difficult to get too, but well worth it.","/images/killerkayaking.jpg",northAmerica,northAmerica2);
        Trek na4 = new Trek("Mr.Toads Wild Ride","5/5","You may think this is a Disney ride by the name but you would be gravely mistaken. Mr.Toads Wild Ride is a single-track mountain bike route that is mostly downhill from Tahoe Rim Trail, Lake Tahoe.The total descent is over 2000 ft. The path itself is not for the faint of heart with steep drops, sections of nothing but rock, and large jumps.","Amazing, definitely recommend but be forewarned this is not for beginners. I have years of offroad biking experience and there were several parts in the trail with between the speed and obstacle I was certain I was about to crash.","/images/killerkayaking.jpg",northAmerica,northAmerica2);
        Trek sa1 = new Trek("Diving With Hammerhead Sharks in the Galapagos","5/5","The distinctive face of the hammerhead shark is one of the great wonders of nature, and in the waters around the Galapagos Islands, there are some of the best diving spots for encounters with these majestic marine animals anywhere in the world.","Being surrounded by hundreds of these sharks is terrifying and exciting.","/images/killerkayaking.jpg",southAmerica,southAmerica1);
        Trek sa2 =new Trek("Infamous Death Road","5/5","One of the most surprising attractions in Bolivia is also one of its most notorious, with the cliff side road once being hailed as the most dangerous road in the world. It is now one of the most exciting mountain biking routes in the region. We were 4 people with mountain bike experience varying from beginner to advanced. Our guides were very accommodating and helpful. I never felt in danger!","review","image",southAmerica,southAmerica1);
        Trek sa3 = new Trek("Chile's Rio Futaleufu","3/5","Believed to be one of the best whitewater rafting rivers in the world, the Rio Futaleufu is a stunning river flowing through the Andes, and featuring some dramatic Grade III, IV and V rapids that will challenge even experienced rafters.","One of the most beautiful, pristine places we have ever been. It's a bit of a commitment to get there, so if you can, allow extra days because there is plenty to see and do. We were a bit nervous about class 4 and 5 rapids, but WOW! what a thrill!","image",southAmerica,southAmerica2);
        Trek sa4 = new Trek("Atacama Desert, Chile","4/5","he world's driest desert is only a short distance outside the town of San Pedro de Atacama. There are seemingly endless sand dunes north of town where you can try this variant of surfing, and see how you cut the slopes up with your moves. ","We absolutely loved our sandboarding experience, the lesson at the start was good and then you were given advice on how to improve every time you came back up. If you are willing to you can make so much out of this by making sure you head straight back up the dune every time.","image",southAmerica,southAmerica2);
        Trek e1 = new Trek("Zip Line, Snowdonia","2/5","Set in North Wales near the stunning Snowdon range, in what once was the world’s largest slate quarry, Penrhyn Quarry is now home to the fastest zip line in the world, 100mph, where you can fly 500m above the bright blue quarry lake.","We did the zipline and it was absolutely amazing. The staff was friendly and helpful from beginning to the end. Everything went smoothly, without any delays; the activity started right at the time we booked, and ended 2 hours later as advertised. We were super lucky, as the weather was clear and sunny. ","image",europe,europe1);
        Trek e2 = new Trek("Running with the Bulls","5/5","You’ve heard of running with the bulls in Pamplona,then run through the streets of the city with dozens of aggressive bulls nicking at your heels. We do warn you, though, injuries are common, so make sure this is one of those adrenaline activities you want to attempt.","The tour was a terrific experience. I would not have seen everything they showed me on my own.","image",europe,europe1);
        Trek e3 = new Trek("Rally Driving, Knockhill","4/5","Petrol heads, this is your calling. If you ever wanted to learn how to be a proper rally driver, give this a try. In two-and-a-half hours, you will have a driving lesson with a professional. Then you’ll take the wheel.","Had an absolutely fantastic day in the new fiesta st s. Great instruction  will definitely be back soon.","image",europe,europe2);
        Trek e4 = new Trek("Hang Gliding Sierra Nevada Spain","3/5","Hang gliding is one of the best adrenaline activities available, but we warn you: try it once and you might become obsessed. Experience Sierra Nevada National Park from the sky with a tandem paragliding flight from Granada. This is an incredible experience that you will never forget!","Amazing experience and some of the most incredible scenery in the world.","image",europe,europe2);
        Trek a1 = new Trek("title1","difficulty","description","review","image",asia,asia1);
        Trek a2 = new Trek("title2","difficulty","description","review","image",asia,asia1);
        Trek a3 = new Trek("title3","difficulty","description","review","image",asia,asia2);
        Trek a4 = new Trek("title4","difficulty","description","review","image",asia,asia2);
        Trek ant1 = new Trek("title1","difficulty","description","review","image",antarctica,antarctica1);
        Trek ant2 = new Trek("title2","difficulty","description","review","image",antarctica,antarctica1);
        Trek ant3 = new Trek("title3","difficulty","description","review","image",antarctica,antarctica2);
        Trek ant4 = new Trek("title4","difficulty","description","review","image",antarctica,antarctica2);
        Trek af1 = new Trek("title1","difficulty","description","review","image",africa,africa1);
        Trek af2 = new Trek("title2","difficulty","description","review","image",africa,africa1);
        Trek af3 = new Trek("title3","difficulty","description","review","image",africa,africa2);
        Trek af4 = new Trek("title4","difficulty","description","review","image",africa,africa2);
        Trek aus1 = new Trek("title1","difficulty","description","review","image",australia,australia1);
        Trek aus2 = new Trek("title2","difficulty","description","review","image",australia,australia1);
        Trek aus3 = new Trek("title3","difficulty","description","review","image",australia,australia2);
        Trek aus4 = new Trek("title4","difficulty","description","review","image",australia,australia2);
        trekRepo.save(na1);
        trekRepo.save(na2);
        trekRepo.save(na3);
        trekRepo.save(na4);
        trekRepo.save(sa1);
        trekRepo.save(sa2);
        trekRepo.save(sa3);
        trekRepo.save(sa4);
        trekRepo.save(e1);
        trekRepo.save(e2);
        trekRepo.save(e3);
        trekRepo.save(e4);
        trekRepo.save(a1);
        trekRepo.save(a2);
        trekRepo.save(a3);
        trekRepo.save(a4);
        trekRepo.save(ant1);
        trekRepo.save(ant2);
        trekRepo.save(ant2);
        trekRepo.save(ant3);
        trekRepo.save(ant4);
        trekRepo.save(af1);
        trekRepo.save(af2);
        trekRepo.save(af3);
        trekRepo.save(af4);
        trekRepo.save(aus1);
        trekRepo.save(aus2);
        trekRepo.save(aus3);
        trekRepo.save(aus4);
    }
}